version: '3'
services:
  cp_postgres:
    container_name: cp_postgres
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  users-service:
    container_name: app
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: build/Dockerfile
    restart: always
    networks:
      - users-main
    volumes:
      - ./config/configs.yaml:/app/config/config.yaml:ro
networks:
  users-main:
    driver: bridge
volumes:
  postgres-vol:
